basePath: /
definitions:
  models.Rating:
    properties:
      description:
        type: string
      id:
        description: id de l'utilisateur
        type: string
      note:
        type: integer
    type: object
info:
  contact:
    email: vincent.gimbert@yahoo.fr
    name: Vincent GIMBERT.
  description: API to manage ratings.
  title: Rating API
  version: 1.0.0
paths:
  /ratings:
    delete:
      description: Delete a rating.
      parameters:
      - description: Collection UUID formatted ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "204":
          description: No Content
        "422":
          description: Cannot parse id
        "500":
          description: Something went wrong
      summary: Delete a rating.
      tags:
      - ratings
    get:
      description: Get ratings.
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Rating'
            type: array
        "500":
          description: Something went wrong
      summary: Get ratings.
      tags:
      - ratings
    post:
      description: Create a rating. UUID is automatically generated
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Rating'
        "422":
          description: Cannot parse id
        "500":
          description: Something went wrong
      summary: Create a rating.
      tags:
      - ratings
  /ratings/{id}:
    get:
      description: Get a rating.
      parameters:
      - description: Collection UUID formatted ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Rating'
        "422":
          description: Cannot parse id
        "500":
          description: Something went wrong
      summary: Get a rating.
      tags:
      - ratings
    put:
      description: Update a rating.
      parameters:
      - description: Collection UUID formatted ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
        "422":
          description: Cannot parse id
        "500":
          description: Something went wrong
      summary: Update a rating.
      tags:
      - ratings
schemes:
- http
swagger: "2.0"
